# Generated by Django 3.0.2 on 2022-02-20 14:50

from django.db import migrations

def addRow(apps, schema_editor):
    
    Movie = apps.get_model('api', 'Movie')
    newMovie = Movie(name="Bourne Identity", desc="A man has forgotten about his past and has teamed up with a girl to know about it.", release_date="2004-07-12", like=0)
    newMovie.save()

    Actor = apps.get_model('api', 'Actor')
    matt = Actor.objects.get(name="Matt Damon")

    Linking = apps.get_model('api', 'Linking')
    newLink = Linking(movie_id=newMovie.id, actor_id=matt.id)
    #newLink.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(addRow),
    ]
